<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="failuremodel" nsURI="http://palladiosimulator.org/failuresmodel/1.0"
    nsPrefix="failuremodel">
  <eSubpackages name="failurescenario" nsURI="http://palladiosimulator.org/failurescenario/1.0"
      nsPrefix="failurescenario">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="FailureScenarioRepository" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="failurescenarios" upperBound="-1"
          eType="#//failurescenario/FailureScenario" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FailureScenario" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="occurrences" upperBound="-1"
          eType="#//failurescenario/Occurrence" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionEnabled" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
          defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Occurrence">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="ensureCorrectOrigin"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="ensureCorrectOrigin" value="( self.origin.oclIsTypeOf(LinkingResourceReference) and ( self.failure.oclIsKindOf(failuretype::LinkFailure) ) )&#xA;or&#xA;( self.origin.oclIsTypeOf(ProcessingResourceReference) and ( self.failure.oclIsKindOf(failuretype::HWFailure) ) )&#xA;or&#xA;( self.origin.oclIsTypeOf(InternalActionReference) and ( self.failure.oclIsKindOf(failuretype::SWFailure) ) )"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="failure" lowerBound="1"
          eType="#//failuretype/Failure"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="origin" lowerBound="1"
          eType="#//failurescenario/Reference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pointInTime" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/PCMRandomVariable"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Reference" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="LinkingResourceReference" eSuperTypes="#//failurescenario/Reference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkingResource" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/LinkingResource"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InternalActionReference" eSuperTypes="#//failurescenario/Reference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="internalAction" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//seff/InternalAction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessingResourceReference" eSuperTypes="#//failurescenario/Reference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="processingResource" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ProcessingResourceSpecification"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="failuretype" nsURI="http://palladiosimulator.org/failuretype/1.0"
      nsPrefix="failuretype">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="FailureTypeRepository" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="In this repository all failures can be created to use them later in a scenario."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="failuretypes" upperBound="-1"
          eType="#//failuretype/Failure" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Failure" abstract="true" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eOperations name="getSupportedElementType" lowerBound="1" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SWFailure" abstract="true" eSuperTypes="#//failuretype/Failure">
      <eOperations name="getSupportedElementType" lowerBound="1" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HWFailure" abstract="true" eSuperTypes="#//failuretype/Failure">
      <eOperations name="getSupportedElementType" lowerBound="1" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LinkFailure" abstract="true" eSuperTypes="#//failuretype/Failure">
      <eOperations name="getSupportedElementType" lowerBound="1" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Domain" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Content" abstract="true" eSuperTypes="#//failuretype/Domain">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="degreeOfCorruption" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Timing" abstract="true" eSuperTypes="#//failuretype/Domain">
      <eStructuralFeatures xsi:type="ecore:EReference" name="delay" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/PCMRandomVariable"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scalingFactor" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/PCMRandomVariable"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Crash" abstract="true" eSuperTypes="#//failuretype/Domain"/>
    <eClassifiers xsi:type="ecore:EClass" name="Mode" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Transient" abstract="true" eSuperTypes="#//failuretype/Mode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="One-time termination, or for the specified duration."/>
      </eAnnotations>
      <eTypeParameters name="Failuretype">
        <eBounds eClassifier="#//failuretype/Failure"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="duration" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/PCMRandomVariable"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="decoratedFailure" lowerBound="1">
        <eGenericType eTypeParameter="#//failuretype/Transient/Failuretype"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Permanent" abstract="true" eSuperTypes="#//failuretype/Mode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Permanent Failure"/>
      </eAnnotations>
      <eTypeParameters name="Failuretype">
        <eBounds eClassifier="#//failuretype/Failure"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="decoratedFailure" lowerBound="1">
        <eGenericType eTypeParameter="#//failuretype/Permanent/Failuretype"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Byzantine" abstract="true" eSuperTypes="#//failuretype/Mode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="probabilityOfOccurence"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SWContentFailure" eSuperTypes="#//failuretype/SWFailure #//failuretype/Content"/>
    <eClassifiers xsi:type="ecore:EClass" name="SWTimingFailure" eSuperTypes="#//failuretype/SWFailure #//failuretype/Timing"/>
    <eClassifiers xsi:type="ecore:EClass" name="SWCrashFailure" eSuperTypes="#//failuretype/SWFailure #//failuretype/Crash"/>
    <eClassifiers xsi:type="ecore:EClass" name="SWPermanentCrashFailure">
      <eGenericSuperTypes eClassifier="#//failuretype/SWFailure"/>
      <eGenericSuperTypes eClassifier="#//failuretype/Crash"/>
      <eGenericSuperTypes eClassifier="#//failuretype/Permanent">
        <eTypeArguments eClassifier="#//failuretype/SWCrashFailure"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SWTransientCrashFailure">
      <eGenericSuperTypes eClassifier="#//failuretype/SWFailure"/>
      <eGenericSuperTypes eClassifier="#//failuretype/Crash"/>
      <eGenericSuperTypes eClassifier="#//failuretype/Transient">
        <eTypeArguments eClassifier="#//failuretype/SWCrashFailure"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HWContentFailure" eSuperTypes="#//failuretype/HWFailure #//failuretype/Content"/>
    <eClassifiers xsi:type="ecore:EClass" name="HWTimingFailure" eSuperTypes="#//failuretype/HWFailure #//failuretype/Timing"/>
    <eClassifiers xsi:type="ecore:EClass" name="HWCrashFailure" eSuperTypes="#//failuretype/HWFailure #//failuretype/Crash"/>
    <eClassifiers xsi:type="ecore:EClass" name="HWPermanentNAFailure">
      <eGenericSuperTypes eClassifier="#//failuretype/HWFailure"/>
      <eGenericSuperTypes eClassifier="#//failuretype/Crash"/>
      <eGenericSuperTypes eClassifier="#//failuretype/Permanent">
        <eTypeArguments eClassifier="#//failuretype/HWCrashFailure"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HWTransientNAFailure">
      <eGenericSuperTypes eClassifier="#//failuretype/HWFailure"/>
      <eGenericSuperTypes eClassifier="#//failuretype/Crash"/>
      <eGenericSuperTypes eClassifier="#//failuretype/Transient">
        <eTypeArguments eClassifier="#//failuretype/HWCrashFailure"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LinkContentFailure" eSuperTypes="#//failuretype/LinkFailure #//failuretype/Content"/>
    <eClassifiers xsi:type="ecore:EClass" name="LinkTimingFailure" eSuperTypes="#//failuretype/LinkFailure #//failuretype/Timing"/>
    <eClassifiers xsi:type="ecore:EClass" name="LinkArbitraryFailure" eSuperTypes="#//failuretype/LinkFailure #//failuretype/Byzantine">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The byzantine failure probability generates one of the stored failure types when triggered."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="noLinkArbitraryFailureAllowedForInternalPossibleFailuresDescription"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="noLinkArbitraryFailureAllowedForInternalPossibleFailuresDescription"
            value="not (self.possibleFailures -> exists(oclIsTypeOf(LinkArbitraryFailure)))"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="possibleFailures" lowerBound="1"
          upperBound="-1" eType="#//failuretype/LinkFailure"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LinkCrashFailure" eSuperTypes="#//failuretype/LinkFailure #//failuretype/Crash"/>
    <eClassifiers xsi:type="ecore:EClass" name="LinkTransientCrashFailure">
      <eGenericSuperTypes eClassifier="#//failuretype/LinkFailure"/>
      <eGenericSuperTypes eClassifier="#//failuretype/Crash"/>
      <eGenericSuperTypes eClassifier="#//failuretype/Transient">
        <eTypeArguments eClassifier="#//failuretype/LinkCrashFailure"/>
      </eGenericSuperTypes>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
